### ISSUE TITLE
class CrowdSaleInterface should have more generic class name

### ISSUE THREAD

**Issue by sojinkim-icon** [sink772/IRC2-token-standard#1]
https://github.com/sink772/IRC2-token-standard/blob/c7c1f8a0e35d55b8a412578f7794223a2bc0c461/mySampleToken/mySampleToken.py#L32

Because it can be any contract, having more generic name would be preferable.

**Comment by sink772** [comment]
I agree. I will change the name.

**Comment by sink772** [comment]
Fixed at bf7cff8
